### ISSUE TITLE
Some encoding problem

### ISSUE THREAD

**Issue by Hydrion-Qlz** [lqtri/WebPage-Segmentation--WPS-#1]
when test the homepage of the CSDN, it went wrong
```python
python WPS_DB_Test.py https://www.csdn.net/
```

i got the log as  follows:
```python
Traceback (most recent call last):
  File "D:\TEMP\WebPage-Segmentation--WPS--main\WebPage-Segmentation--WPS--new\WPS_DB_Test.py", line 39, in <module>
    main()
  File "D:\TEMP\WebPage-Segmentation--WPS--main\WebPage-Segmentation--WPS--new\WPS_DB_Test.py", line 20, in main
    wpsdb = Wpsdb.Wpsdb(unquote(sys.argv[1], encoding="utf-8"))
  File "D:\TEMP\WebPage-Segmentation--WPS--main\WebPage-Segmentation--WPS--new\WPS_DB.py", line 36, in __init__
    self.getDomTree()
  File "D:\TEMP\WebPage-Segmentation--WPS--main\WebPage-Segmentation--WPS--new\WPS_DB.py", line 118, in getDomTree
    self.toHTMLFile(self.browser.page_source)
  File "D:\TEMP\WebPage-Segmentation--WPS--main\WebPage-Segmentation--WPS--new\WPS_DB.py", line 114, in toHTMLFile
    file.write(str(page_source))
UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 125149: illegal multibyte sequence
```

> i'm not familar with the PR operation，so i just leave an issue

from the log it can be easily found that it's the encoding problem, i just add `encoding='utf-8'` and the problem has been solved, there are two places with this problem
- `ImageOut.py: line15`
- `WPS_DB.py: line13`

**Comment by Hydrion-Qlz** [comment]
One more problem，`beautifulsoup4` in requirements.txt has been misspelled
